### ISSUE TITLE
 Problem with composer

### ISSUE THREAD

**Issue by ghost** [TruckersMP/API-Client#21]
Hello,
When I run the Composer command I get errors

`composer require truckersmp/api-client
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.2 for truckersmp/api-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package truckersmp/api-client No version set (parsed as 1.0.0) is satisfiable by truckersmp/api-client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for truckersmp/api-client ^1.2 -> satisfiable by truckersmp/api-client[v1.2.0].
    - truckersmp/api-client v1.2.0 requires nesbot/carbon ^2.16 -> satisfiable by nesbot/carbon[2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.17.0, 2.17.1, 2.18.0, 2.19.0, 2.19.1, 2.19.2, 2.20.0, 2.21.0, 2.21.1, 2.21.2, 2.21.3, 2.22.0, 2.22.0-beta.1, 2.22.0-beta.2, 2.22.0-beta.3, 2.22.1, 2.22.2, 2.22.3, 2.23.0, 2.23.0-beta.1, 2.23.0-beta.2, 2.23.0-beta.3, 2.23.0-beta.4, 2.23.1, 2.24.0, 2.24.0-beta.1, 2.24.0-beta.2, 2.24.0-beta.3, 2.24.0-beta.4, 2.25.0, 2.25.0-beta.1, 2.25.0-beta.2, 2.25.0-beta.3, 2.25.1, 2.25.2, 2.25.3, 2.26.0, 2.27.0, 2.28.0, 2.28.0-beta.1, 2.29.0, 2.29.1, 2.30.0, 2.31.0, 2.32.0, 2.32.1, 2.32.2, 2.33.0, 2.34.0, 2.34.1, 2.34.2, 2.35.0, 2.36.0, 2.36.1, 2.37.0, 2.38.0, 2.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.`

**Comment by bensherred** [comment]
Hi @xElten,

Thanks for raising this issue. Please can you post the contents of your `composer.json` file so I can take a further look?

**Comment by ghost** [comment]
> Hi @xElten,
> 
> Thanks for raising this issue. Please can you post the contents of your `composer.json` file so I can take a further look?

{
  "name": "truckersmp/api-client",
  "description": "TruckersMP API Library helps connecting to and using the TruckersMP API.",
  "homepage": "https://truckersmp.com/",
  "license": "MIT",
  "authors": [
    {
      "name": "HumaneWolf",
      "email": "humanewolf@truckersmp.com",
      "homepage": "https://humanewolf.com/",
      "role": "CM/Dev"
    },
    {
      "name": "Thor Erik (Tuxy Fluffyclaws) Lie",
      "email": "tuxy@truckersmp.com",
      "homepage": "https://truckersmp.com/",
      "role": "Dev"
    },
    {
      "name": "CJMAXiK",
      "email": "me@cjmaxik.ru",
      "homepage": "https://cjmaxik.ru",
      "role": "IGA/Dev"
    }
  ],
  "require": {
    "php": ">=5.6.0",
    "nesbot/carbon": "^1.21",
    "php-http/message": "^1.2",
    "guzzlehttp/psr7": "^1.3"
  },
  "require-dev": {
    "phpunit/phpunit": "^5.3",
    "squizlabs/php_codesniffer": "^2.6",
    "php-http/guzzle6-adapter": "^1.0"
  },
  "autoload": {
    "psr-4": {
      "TruckersMP\\": "src/"
    },
    "classmap": [
      "src/"
    ]
  },
  "autoload-dev": {
    "psr-4": {
      "TruckersMP\\Tests\\API\\": "tests/"
    }
  },
  "scripts": {
    "test": [
      "./vendor/bin/phpunit",
      "./vendor/bin/phpcs src --standard=PSR2",
      "./vendor/bin/phpcs Tests --standard=PSR2"
    ]
  }
}

**Comment by bensherred** [comment]
@xElten, this looks to be the `composer.json` of the package rather than your project. Would you be able to post the contents of your `composer.json` which should be in the root of your project?

**Comment by ghost** [comment]
What do you mean exactly. i have this file in my project folder

**Comment by bensherred** [comment]
Are you trying to use the package within your application, or are you trying to contribute towards the package?

**Comment by cjmaxik** [comment]
Did you try to do `composer require truckersmp/api-client` in this project's folder?

**Comment by xElten** [comment]
yes

**Comment by ghost** [comment]
I'm trying to test this package and later i would like to use it in my project

**Comment by ghost** [comment]
@bensherred i only have this composer.json i dont have an other composer.json file

**Comment by cjmaxik** [comment]
Please share the screenshot of your project folder.

**Comment by ghost** [comment]
this folder looks like in the github project

**Comment by bensherred** [comment]
@xElten from what I can tell you have cloned this repo and then tried to run `composer require truckersmp/api-client`, which is not the way composer works. What you need to do is just run `composer require truckersmp/api-client` in the root of your project without cloning this repo. I'd try running the command in a blank folder first.

**Comment by cjmaxik** [comment]
Well, this is not the right way to use this package.

If you don't have any projects yet, do this thing:
- `composer init` in the empty project folder
- `composer require truckersmp/api-client` to add this package in your project.
Then you'd be able to use it via autoload.
