### ISSUE TITLE
Add support for VTC Events

### ISSUE THREAD

**Issue by PenguinNexus** [TruckersMP/API-Client#22]
Under https://github.com/TruckersMP/API-Client/wiki/Company-Request there doesn't appear to be any information regarding VTC Events - Could this functionality be supported by this client please?

**Comment by PenguinNexus** [comment]
Will attempt to PR this one

**Comment by bensherred** [comment]
It should be pretty easy to add this functionality.

You'll need to crate a couple of models. One for the an event and another for an attendee. Once you have those you'll be able to create a request class and add a method to the main Client class.

Let me know if you don't get round to it and I'll take a look at implementing it 😊

Don't forget those tests 😉

**Comment by bensherred** [comment]
Hey @PenguinNexus,

Just wondering if you got round to giving this a go? 👀

**Comment by PenguinNexus** [comment]
Hey @bensherred I did but didn't get far enough where I could consider creating the pull request.

**Comment by bensherred** [comment]
No worries, do you still plan to finish it?

**Comment by PenguinNexus** [comment]
Sadly not, I no longer have the time to do so, sorry. I'm happy to send you what I have so far

**Comment by bensherred** [comment]
Okay no worries, I can see your fork so I will take a look through that 😄

**Comment by ShawnCZek** [comment]
Sorry that it took a bit longer, there was a little communication error about the next breaking version.
