### ISSUE TITLE
player()->get() throws a server error on player ID which not regtistered on TruckersMP

### ISSUE THREAD

**Issue by viiper94** [TruckersMP/API-Client#23]
On https://github.com/TruckersMP/API-Client/blob/master/src/Requests/PlayerRequest.php#L56 method expects `response` parameter as array, but if player do not exist under that ID API returns `response` as a string.

**Comment by bensherred** [comment]
@viiper94 this has been fixed as part of #26, although it hasn’t been released yet

**Comment by ShawnCZek** [comment]
Sorry that it took a bit longer, there was a little communication error about the next breaking version.
