### ISSUE TITLE
Use guzzlehttp/guzzle instead of php-http/guzzle6-adapter

### ISSUE THREAD

**Issue by PenguinNexus** [TruckersMP/API-Client#24]
If possible, could guzzlehttp/guzzle be used? This would be more consistent with other uses within the Laravel Framework. php-http/guzzle6-adapter is not required by https://github.com/TruckersMP/Steam-Socialite so I am unsure why it is needed here.

C:\laragon\www\plasmagaming>composer require truckersmp/api-client
Using version ^1.2 for truckersmp/api-client
./composer.json has been updated
Running composer update truckersmp/api-client
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-http/guzzle6-adapter[dev-master, v1.0.0, ..., v1.1.1, v2.0.0, ..., v2.0.2] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but the package is fixed to 7.3.0 (lock file version) by a partial
 update and that version does not match. Make sure you list it as an argument for the update command.
    - truckersmp/api-client v1.2.0 requires php-http/guzzle6-adapter ^1.0 || ^2.0 -> satisfiable by php-http/guzzle6-adapter[v1.0.0, v1.1.0, v1.1.1, v2.0.0, v2.0.1, v2.0.2, 2.x-dev (alias of dev-master)].
    - php-http/guzzle6-adapter 2.x-dev is an alias of php-http/guzzle6-adapter dev-master and thus requires it to be installed too.
    - Root composer.json requires truckersmp/api-client ^1.2 -> satisfiable by truckersmp/api-client[v1.2.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by bensherred** [comment]
That shouldn't be a problem, I'll do some investigating now 😄

**Comment by bensherred** [comment]
@PenguinNexus this has been implemented and merged but not yet released. It will most likely be part of a new major release 😄

**Comment by iDiegoNL** [comment]
This issue should be closed if I'm not mistaken, #26 has been merged which resolved this problem.

**Comment by ShawnCZek** [comment]
@iDiegoNL: It has not been merged to master yet. That is why I have kept this issue open.

**Comment by ShawnCZek** [comment]
Sorry that it took a bit longer, there was a little communication error about the next breaking version.
