### ISSUE TITLE
How can i set this up

### ISSUE THREAD

**Issue by DeniPEKSEN** [TruckersMP/API-Client#43]
Hello,
 I tryed to set this up also i run the composer command given on the instruction given but it did not work what should i do

**Comment by bensherred** [comment]
Hi @DeniPEKSEN,

Please can you provide us with a screenshot of the error you received.

**Comment by DeniPEKSEN** [comment]
Hello again,

It does not give an error just composer is not launching and as i said i dont know how to setup this

**Comment by bensherred** [comment]
Hi @DeniPEKSEN,

This seems to be an issue with your local setup of composer rather than with our package. Therefore I am going to close this issue. You can refer to the composer website on how to install and use composer https://getcomposer.org
